// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaCr0Q3hDwIx7U0k7DVh5n9oslwQMvzLc',
    appId: '1:1097301732284:web:682933ba42fbeb97ca19b9',
    messagingSenderId: '1097301732284',
    projectId: 'nom-nom-eats',
    authDomain: 'nom-nom-eats.firebaseapp.com',
    storageBucket: 'nom-nom-eats.appspot.com',
    measurementId: 'G-0K0Z4YY29T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKZqesV5k0yX5WBCcbC6tSynM1rGDl570',
    appId: '1:1097301732284:android:28dbabfd165580a5ca19b9',
    messagingSenderId: '1097301732284',
    projectId: 'nom-nom-eats',
    storageBucket: 'nom-nom-eats.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6aP7XQRzY83UYGkgsMBGcfTfI6F3IpTs',
    appId: '1:1097301732284:ios:a66e8acd9ec8e0c9ca19b9',
    messagingSenderId: '1097301732284',
    projectId: 'nom-nom-eats',
    storageBucket: 'nom-nom-eats.appspot.com',
    iosBundleId: 'com.example.nomNomEats',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6aP7XQRzY83UYGkgsMBGcfTfI6F3IpTs',
    appId: '1:1097301732284:ios:a66e8acd9ec8e0c9ca19b9',
    messagingSenderId: '1097301732284',
    projectId: 'nom-nom-eats',
    storageBucket: 'nom-nom-eats.appspot.com',
    iosBundleId: 'com.example.nomNomEats',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaCr0Q3hDwIx7U0k7DVh5n9oslwQMvzLc',
    appId: '1:1097301732284:web:26b595f050ac4233ca19b9',
    messagingSenderId: '1097301732284',
    projectId: 'nom-nom-eats',
    authDomain: 'nom-nom-eats.firebaseapp.com',
    storageBucket: 'nom-nom-eats.appspot.com',
    measurementId: 'G-CEV90X66V2',
  );
}
